### ISSUE TITLE
Load presentation using filename/path

### ISSUE THREAD

**Issue by phuvf** [phuvf/oscpoint#15]

**Comment by Total-Image** [comment]
Would be very usefull!

**Comment by robertskiba** [comment]
Hi guys,

I was just testing this plugin and I wondered that the developer could forget the two most important functions for the powerpoint plugin: Opening and closing a file.

I've been working with Remote Show Control over the years and that function often spares a complete person in the preseting workflow because changing PPTs only needs 2 seconds maximum. Since then, I don't even need the PPT-Laptops physically close to my position any more. (For remote Control KVM I use the NDI-Tools with KVM). 

So I would be very happy and spend lots of coffee if this could be implemented.

**Comment by phuvf** [comment]
@robertskiba (and all others who have made suggestions here) - thanks for the note and the suggestion.

The initial version of OSCPoint was designed to solely work within the boundaries of the PowerPoint Object model, and not interact with the filesystem at all - hence why this feature was not included. Having said that, there's obviously a lot of interest in this feature and it's obviously possible, so I'll put it at the top of the road map.

To get this right, I'd appreciate some feedback on how should we reference files? This can be:

1. Just by send the full path "C:\stuff\my.pptx" - or -
2. We could designate a working directory using one OSC command e.g. /oscpoint/setDirectory "My Powerpoint Files". This would allow a feedback that lists all the PPTX files in the directory, which could be useful. A separate command would then open the file.

Additionally, should we support having multiple show files open at once, and switching between them, or should we close one file when we open another?

If we have a working directory concept, should this be based off the user folder, the user's desktop folder? Any other suggestions?

**Comment by robertskiba** [comment]
Hi Nick, 

thank you a lot for your hard work and effort to make a tool like this. 

In RSC, you always had to enter the whole path to the ppts. This should still be possible but much better would be if there would be a “default path” option with a selectable default path where your plugin could either scan for ppt and pptx or the user could enter a file name. Many operators work with file sync tools like sync thing so this would be a great option. 

I would wish the following commands for your plugin:


- open ppt file (with or without instantly running the file as an option and an option to close all other currently opened files)
- Close ppt file (with an option to avoid closing if changes were made and have not been saved)
- Rescan default directory for new files (only rescan the above option if this command has been triggered)
- for some rare occasion it could be interesting to create a command to rename or delete files, but I have never missed something like this. 

And to be true: I earn money with using tools like this so I would really be ok with a payment for the tool to support your efforts

**Comment by jhartikhainen** [comment]
Hi Nick!

Just to give you an example, on shows/events I always name my PowerPoint by number and then the time when it's scheduled, and then sometimes I leave the name there as well but it's not important to me as usually when the client comes and ask about his/her slides, instead of asking their name I ask what time is your presentation and then I can easily find it... So usually the path is: "G:\My Drive\Name of a show\1.pptx" ... And usually I ask in advance to label the PPTs with numbers and their name, nothing else.
Also like the previous comment would be happy to make a payment and when there are updates after a year happy to pay for the updates but not as a SaaS

**Comment by jhartikhainen** [comment]
> "Additionally, should we support having multiple show files open at once, and switching between them, or should we close one file when we open another?
> 
> If we have a working directory concept, should this be based off the user folder, the user's desktop folder? Any other suggestions?"

I don't know do I get the question right, but having multiple show files open at once should be useful (as I have had plenty of shows where the client wants to have two confidence monitors, and both PPTs running at the same time). Usually, I run two laptops simultaneously controlled with perfectcue then. But just switching between them PPTs is a "job" then. 

I think the user folder option should be good, so in that case, I can use google drive/onedrive folder for it. Just at the beginning of the show I have to pick the right folder.

**Comment by Total-Image** [comment]
Since the "Load presentation using filename/path" function is not yet implemented, I wonder how others load a presentation (automatically and not using a remote desktop application) on a remote machine? And what if PowerPoint is not running. Can we check somehow if PowerPoint is running and if not start the PowerPoint application on a remote machine? Using a batch script?

**Comment by robertskiba** [comment]
I can suggest the mixed use of the free "Remote Show control" plugin by Irisdown (that doesn't use OSC) and OSCPoint. Works fine and stable.

**Comment by robertskiba** [comment]
To open PPT you can use Vicreo Listener. But also some local tools like a Powerpoint watchdog that reopens PPT if the process can't be found may be a solution (google for it!)

You can check if PPT is open if you get a response by OSCPoint in many variables.

**Comment by phuvf** [comment]
Added in v2.x
