### ISSUE TITLE
Slideshow window issue when starting slideshow from named section

### ISSUE THREAD

**Issue by phuvf** [phuvf/oscpoint#38]
Running on Windows 11, I start PowerPoint via Companion using Run Shell Path (local) and with the command line /c and the deck's file name. PowerPoint opens fine. When I then use OSCPoint Start Slideshow with a named section, PowerPoint drops into slideshow correctly, but does not display on the PC 2nd screen for streaming. If I close PowerPoint and manually reopen it, all works fine. Any suggestions?

**Comment by phuvf** [comment]
Also, it'd be interesting to see the add-in logs for the machine when this happens. Feel free to add them in here.

**Comment by ChrisSW58** [comment]
Thanks for the response. A couple of clarifications. I’m using named sections rather than specific slide numbers. Secondly, with no change in code, I restart PowerPoint and press the same button to start at the same section, and it all works. I’m not convinced it is a OSCPoint problem but I’m not the expert!

**Comment by ChrisSW58** [comment]
> Also, it'd be interesting to see the add-in logs for the machine when this happens. Feel free to add them in here.

Will try to get them later today if possible

**Comment by phuvf** [comment]
> Thanks for the response. A couple of clarifications. I’m using named sections rather than specific slide numbers. Secondly, with no change in code, I restart PowerPoint and press the same button to start at the same section, and it all works. I’m not convinced it is a OSCPoint problem but I’m not the expert!

When you start from a named section, OSCPoint loops through all the sections in the presentation to find a section with a matching name. If it finds one, it uses the first slide information of the section to work out which slide to start from - then jumps to this slide number.

So the control between OSCPoint and PowerPoint itself is still a slide number request, even in this situation.

**Comment by ChrisSW58** [comment]
> > Thanks for the response. A couple of clarifications. I’m using named sections rather than specific slide numbers. Secondly, with no change in code, I restart PowerPoint and press the same button to start at the same section, and it all works. I’m not convinced it is a OSCPoint problem but I’m not the expert!
> 
> When you start from a named section, OSCPoint loops through all the sections in the presentation to find a section with a matching name. If it finds one, it uses the first slide information of the section to work out which slide to start from - then jumps to this slide number.
> 
> So the control between OSCPoint and PowerPoint itself is still a slide number request, even in this situation.

Thanks for the explanation....however, the interesting item is that the initial OSCPoint call to display the correct slide is correct. On PowerPoint the correct slide moves into slideshow. PowerPoint is in slideshow mode with the correct slide - it just doesn't display on screen 2 where I use PiP control to put it on the screen. A PowerPoint restart, without restarting Companion, resolves the issue. It definitely sounds like a timing issue or incomplete initialisation somewhere.

**Comment by ChrisSW58** [comment]
Apologies for the delay in getting these files to you. A few points:

- The laptop is shut down overnight.
- PowerPoint is started as described and the slide deck opened by Companion when the streaming system is started.
- The issue is intermittent but happens most times. Restarting PowerPoint solves the issue.
- 2024-04-26_oscpoint.log is when PowerPoint is started and does NOT go to the monitor for display on the streaming
- 2024-04-26_oscpoint 2.log is a few seconds later when PowerPoint is restarted and this time it works. Companion was NOT restarted or changed in any way.
- On both occasions, OSCPoint is opening the correct slide in PowerPoint and putting it into slideshow mode on the laptop
[2024-04-26_oscpoint.log](https://github.com/phuvf/oscpoint/files/15129398/2024-04-26_oscpoint.log)
[2024-04-26_oscpoint 2.log](https://github.com/phuvf/oscpoint/files/15129399/2024-04-26_oscpoint.2.log)


I hope that all makes sense!

**Comment by phuvf** [comment]
Fixed in v2.x
