### ISSUE TITLE
Beta v2.0.2.0 : Using 'Start Slide Show>start from>current slide. 

### ISSUE THREAD

**Issue by nisted** [phuvf/oscpoint#51]
Beta v2.0.2.0 : Using 'Start Slide Show>start from>current slide causes ppt to start the slide show as if the current slide was slide number 1.  
For example, currently using a deck with 84 slides. 
Using OSCP as above, and starting at slide 77 starts the presentation at the correct point, but gives a presenter view showing that the presentation is on slide 1 of 8 (the number of remaining slides), and slide navigation back past slide '1' is not possible. 

First seen running a main ppt on stable and backup ppt on beta.  Confirmed issue by switching versions on both machines, and issue travelled with beta version.

**Comment by phuvf** [comment]
Yes, this is expected behaviour due to the way OSCPoint handles `Start from x slide` or `Start from current slide`.

Internally, OSCPoint first edits the slideshow settings for the presentation, setting the starting slide as necessary. This means that it starts on the correct slide without having to display slide 1 first, but it does mean the slides get re-numbered in presenter view.

This isn't ideal and I'll look to find other ways to provide these functions - thanks for drawing my attention to this.

In the meantime, I suggest you chain together a `Start slideshow from beginning` and a `Goto to slide` action to get you where you need to be with all the slides still available.

**Comment by nisted** [comment]
Also just noticed that in the above scenario, while ppt reports slide 1of 8 (instead of 77 of 84), OSC feedback in companion reports slide 1 of 84....

**Comment by phuvf** [comment]
Thanks for the note. I'll take a look.

**Comment by nisted** [comment]
Is that Something that comes with the beta changes, as I don’t experience this behaviour with the stable release?

**Comment by phuvf** [comment]
This behaviour was changed between v1.x and v2.x

I'm going to roll the stable version back to v1.0.1.2 while I think about this issue a bit more.

**Comment by phuvf** [comment]
Reverted back to old method.
